# Etapa de construcción
FROM php:8.2-fpm as builder

# Instalar dependencias del sistema
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    nodejs \
    npm

# Instalar extensiones PHP
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Instalar Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Instalar Yarn
RUN npm install -g yarn

# Copiar archivos
WORKDIR /var/www
COPY . .

# Instalar dependencias
RUN composer install --optimize-autoloader --no-dev
RUN yarn install --production

# Etapa de producción
FROM php:8.2-fpm

# Copiar solo lo necesario desde la etapa de construcción
COPY --from=builder /var/www /var/www

# Configurar permisos
RUN chown -R www-data:www-data /var/www/storage
RUN chown -R www-data:www-data /var/www/bootstrap/cache

# Puerto y comando de inicio
WORKDIR /var/www
EXPOSE 8000
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]